(function () {
  'use strict';
  const SUPABASE_URL = 'https://meulxqleymbjkedaagby.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_8UM9No_56gY8ArX0yb1MmA_XVH-V-mV';
  const PRODUCT_KEYS = {
    'produto-duplix-5mm':'pulseira-duplix-5mm','produto-pulseira-cartier':'pulseira-cartier-2mm','produto-pulseira-grumet':'pulseira-grumet-2-5mm','produto-pulseira-piastrine-3mm':'pulseira-piastrini-3mm','produto-corrente-duplix':'duplix-3mm','produto-cordao-entrelacado':'cordao-baiano-3mm','produto-corrente-veneziana':'veneziana-1mm','produto-corrente-grumet':'grumet-3mm','produto-corrente-cadeado':'cadeado-3mm','produto-corrente-cartier':'cartier-2mm','produto-corrente-elo-portugues':'elo-portugues-2mm','produto-corrente-piastrini':'piastrini-2mm','produto-escapulario-cruz':'escapulario-espirito-santo-cruz','produto-escapulario-jesus-nossa-senhora':'escapulario-nossa-senhora-cristo','produto-duplix-3mm':'pulseira-duplix-3mm','produto-pulseira-veneziana':'pulseira-veneziana-1mm','produto-pulseira-cadeado':'pulseira-cadeado-2-8mm'
  };
  function client(){return window.supabase&&window.supabase.createClient?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;}
  function loadLib(done){if(window.supabase)return done();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=done;s.onerror=()=>console.error('Supabase não carregou.');document.head.appendChild(s);}
  function statusEl(product){let e=product.querySelector('.uzi-live-stock');if(e)return e;e=document.createElement('div');e.className='uzi-live-stock';e.style.cssText='margin:10px 0 14px;font:700 12px/1.4 Arial,sans-serif;letter-spacing:.6px;';const sizes=product.querySelector('.v75-sizes');if(sizes)sizes.insertAdjacentElement('afterend',e);return e;}
  function purchaseButtons(product){return [...product.querySelectorAll('button,a')].filter(el=>{const t=el.textContent.trim().toLowerCase();return t.includes('adicionar ao carrinho')||t.includes('comprar agora');});}
  function syncPurchaseButtons(product,stock){const soldOut=stock<=0;purchaseButtons(product).forEach(btn=>{btn.disabled=soldOut;btn.setAttribute('aria-disabled',String(soldOut));if(soldOut)btn.classList.add('disabled','is-disabled');else btn.classList.remove('disabled','is-disabled');});}
  function syncSizeOptions(product,map){product.querySelectorAll('.v75-size').forEach(size=>{const v=String(size.getAttribute('data-size')||size.textContent.trim()).toLowerCase();const row=map[v];const stock=row?Number(row.stock||0):0;const soldOut=!!row&&stock<=0;size.setAttribute('aria-disabled',String(soldOut));size.classList.toggle('is-sold-out',soldOut);size.style.opacity=soldOut?'0.45':'';size.style.cursor=soldOut?'not-allowed':'';size.style.pointerEvents=soldOut?'none':'';if(soldOut){size.title='Esgotado';if(!size.dataset.originalText)size.dataset.originalText=size.textContent.trim();size.textContent=size.dataset.originalText+' • ESGOTADO';if(size.classList.contains('is-selected'))size.classList.remove('is-selected');}else if(size.dataset.originalText){size.textContent=size.dataset.originalText;size.removeAttribute('title');}});}
  function connect(product,rows){const sizes=product.querySelector('.v75-sizes');if(!sizes)return;const map={};rows.forEach(r=>map[String(r.variant||'Único').toLowerCase()]=r);const st=statusEl(product);function refresh(){syncSizeOptions(product,map);const sel=product.querySelector('.v75-size.is-selected');if(!sel){st.textContent='';return;}const v=String(sel.getAttribute('data-size')||sel.textContent.trim()).toLowerCase();const r=map[v];const n=r?Number(r.stock||0):0;syncPurchaseButtons(product,n);if(n<=0){st.textContent='ESGOTADO';st.style.color='#ff7070';}else if(n<=2){st.textContent='ÚLTIMAS UNIDADES • '+n+' disponível'+(n===1?'':'is');st.style.color='#f3c65b';}else{st.textContent='EM ESTOQUE • '+n+' unidades disponíveis';st.style.color='#62d889';}}sizes.addEventListener('click',()=>setTimeout(refresh,50));refresh();}
  async function load(){const sb=client();if(!sb)return;const products=Object.keys(PRODUCT_KEYS).map(id=>document.getElementById(id)).filter(Boolean);if(!products.length)return;const keys=[...new Set(products.map(p=>PRODUCT_KEYS[p.id]))];const q=await sb.from('inventory_items').select('product_key,variant,stock,active').in('product_key',keys).eq('active',true);if(q.error){console.error('Erro ao consultar estoque:',q.error);return;}const grouped={};(q.data||[]).forEach(r=>{(grouped[r.product_key]||(grouped[r.product_key]=[])).push(r);});products.forEach(p=>{const rows=grouped[PRODUCT_KEYS[p.id]]||[];if(rows.length)connect(p,rows);});}
  function start(){loadLib(load);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();